### ISSUE TITLE
First Attempt Does Not Redirect

### ISSUE THREAD

**Issue by primary0** [kalasjocke/authlogic-facebook-connect#23]
When a new user clicks the Facebook login button, the popup shows. But after pressing "allow" the user is not redirected to the dashboard page. However, after this, if the user refreshes the login page and clicks the Facebook login button again, he is immediately taken to the dashboard (the url bar shows that it first goes to /user_session for authentication - and there is no popup because the application is allowed.)

**Comment by pcasa** [comment]
Having same problem.  Just started doing this.

**Comment by theboogster** [comment]
We are having this issue as well.  Should someone start a bug report?

**Comment by theboogster** [comment]
http://bugs.developers.facebook.com/show_bug.cgi?id=11733

Please confirm this bug and vote for it!

**Comment by primary0** [comment]
Facebook has fixed this bug.

**Comment by rapidos** [comment]
Hi,
I am desperatly lookin all over the web on how to fix this issue. 

When a user clicks Allow, it gets redirected to my callback_url within the popup. The user then needs to close the popup, refresh the website and hit the login button again to get logged in!

Apparently this bug is affecting other people using authlogic+ facebooker 
see the example at http://github.com/holden/authlogic_openid_selector_example

If anyone knows how to fix it I'd love to hear how to do that since I've been struggling with this for the last 2 days ...
